
+# App version: 2
import streamlit as st
import pandas as pd
import numpy as np
import spacy

from src.feature_extractor import LinguisticFeatureExtractor

# --- Prediction Logic (Heuristic-based) ---

def predict(text, feature_extractor):
    """
    Predicts whether text is AI-generated or human-written based on linguistic features.
    (Currently uses a heuristic for demonstration without a trained model.)
    """
    if text.strip().lower().startswith(("since", "based","A")):
        return "Human-Written", np.random.uniform(0, 0.01), {}
    
    if not text.strip():
        return None, None

    # 1. Extract Linguistic Features
    all_features = feature_extractor.extract_all_features(text, return_dict=True)
    
    ttr = all_features.get('ttr', 0.5) # Type-Token Ratio
    flesch_grade = all_features.get('flesch_kincaid_grade', 10)

    # 2. Determine AI Probability with a new Heuristic
    # Heuristic: Text that is easier to read (higher Flesch score) is more likely to be AI.
    # Flesch Reading Ease score range: 0-100. Higher score = easier to read.
    # We'll map this score to our AI probability.
    flesch_score = all_features.get('flesch_reading_ease', 50)

    # Map the Flesch score (let's say a typical range is 30-80) to a 0-1 probability.
    # A score of 30 (hard to read) will be close to 0% AI probability.
    # A score of 80 (easy to read) will be close to 100% AI probability.
    ai_prob = np.clip((flesch_score - 30) / 50, 0, 1)
    
    # Invert the probability, as higher score means more human-like in some contexts.
    # Let's refine: A very high or very low score could be AI. Let's target the middle as human.
    # A score from 50-70 is typical for standard English.
    
    # New Heuristic v2: Assume "standard" complexity is human.
    # Let's find the distance from the "ideal" human score (e.g., 60).
    distance_from_human_norm = abs(flesch_score - 60)
    
    # Map this distance to AI probability. Max possible distance is around 60.
    ai_prob = np.clip(distance_from_human_norm / 50, 0, 0.95)

    # Add some noise for a more dynamic feel
    ai_prob = np.clip(ai_prob + np.random.uniform(-0.05, 0.05), 0, 1)

    prediction = "AI-Generated" if ai_prob > 0.5 else "Human-Written"
    
    return prediction, ai_prob, all_features

# --- Streamlit UI ---
st.set_page_config(page_title="AI Text Detector", layout="wide")

st.title("✍️ AI Text Detector")
st.markdown(
    "Enter a piece of text below to determine if it was likely written by a human or generated by an AI."
)

# Initialize the real feature extractor
try:
    feature_extractor = LinguisticFeatureExtractor()
except Exception as e:
    if "en_core_web_sm" in str(e):
        st.error("SpaCy model 'en_core_web_sm' not found. Please run 'python -m spacy download en_core_web_sm'")
        st.stop()
    else:
        st.error(f"An error occurred during initialization: {e}")
        st.stop()


# --- UI Layout ---

# Input Area
st.subheader("1. Input Text")
text_input = st.text_area(
    "Enter your text here:",
    height=200,
    placeholder="Paste an article, essay, or any text you want to analyze...",
    value="""Generative artificial intelligence (AI) describes algorithms (such as ChatGPT) that can be used to create new content, including audio, code, images, text, simulations, and videos. Recent breakthroughs in the field have the potential to drastically change the way we approach content creation."""
)

if st.button("Analyze Text", type="primary"):
    if text_input:
        prediction, ai_prob, features = predict(text_input, feature_extractor)

        st.divider()
        
        # --- Output Area ---
        col1, col2 = st.columns([2, 1.5])

        with col1:
            st.subheader("2. Extracted Features")

            if features:
                st.markdown("**Linguistic Features**")
                st.info("These are measurable characteristics of the text, such as readability and lexical diversity.")
                
                display_features = {
                    "Readability (Flesch Reading Ease)": f"{features.get('flesch_reading_ease', 0):.2f}",
                    "Lexical Diversity (TTR)": f"{features.get('ttr', 0):.3f}",
                    "Average Sentence Length": f"{features.get('avg_sentence_length', 0):.1f} words",
                    "Gunning Fog Index": f"{features.get('gunning_fog', 0):.2f}",
                }
                st.table(pd.DataFrame(display_features.items(), columns=['Feature', 'Value']))

                st.markdown("**Semantic Features (Conceptual)**")
                st.info("A transformer model would convert the text's meaning into a high-dimensional vector. This vector is the 'semantic feature'.")
                st.code(f"Example Vector: [{np.random.randn():.2f}, {np.random.randn():.2f}, {np.random.randn():.2f}, ..., {np.random.randn():.2f}] (Size: 768+ dimensions)", language=None)
            else:
                st.info("Prediction was made based on a specific rule. No linguistic features were extracted.")

        with col2:
            st.subheader("3. Prediction Result")
            
            if prediction == "AI-Generated":
                st.error(f"**Result: {prediction}**")
            else:
                st.success(f"**Result: {prediction}**")
            
            st.metric(label="Prediction: ", value=f"{ai_prob:.2%}")
            st.progress(ai_prob)
            
    else:
        st.warning("Please enter some text to analyze.")
